# in_features: ${data.dataset.graph.num_nodes} # take the number of nodes from the graph
layers: [10, 10, 10]
dropout: null
num_transforms: 1 # number of transformations to apply (you can change)
residual: false
activation:
  _target_: torch.nn.LeakyReLU
additive: False
normalization:
  _target_: ocd.models.normalization.ActNorm
  _partial_: true

base_distribution:
  _target_: torch.distributions.Normal
  _args_: [0., 1.]

ordering: null
num_post_nonlinear_transforms: 0
