defaults:
  - permutation: gumbel_top_k

cuda: true
checkpointing: null

max_epochs: 100
flow_optimizer:
  _target_: torch.optim.Adam
  lr: 0.01
  weight_decay: 0.1
  _partial_: true

permutation_optimizer: ${.flow_optimizer}

scheduler:
  flow_frequency: 1
  permutation_frequency: 1
  flow_lr_scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: min
    min_lr: 0.00005
    threshold: 0.001
    _partial_: true
  permutation_lr_scheduler: ${.flow_lr_scheduler}

# tracking configurations
data_visualizer: null
brikhoff: null